version: "3.9"

services:
  flask_app:
    build: .
    container_name: kyber_ascon_flask
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
